SELECT * FROM USUARIO ;
SELECT * FROM PERFIL ;
SELECT *  FROM ROLE ;
SELECT * FROM ROLE_PERFIS ;
SELECT * FROM "schema_version";

/*CONSULTA ROLES*/
SELECT u.username, r.role FROM ROLE_PERFIS pr
INNER JOIN PERFIL p ON pr.PERFIS_ID = p.ID 
INNER JOIN USUARIO u ON u.PERFIL_ID = p.ID
INNER JOIN ROLE r ON pr.ROLES_ID = r.id
WHERE u.username = '@carl';

/*CONSULTA USUARIO / PERFIL / ROLES*/
SELECT u.id, u.username, p.id, p.perfil, r.id, r.role FROM ROLE_PERFIS pr
INNER JOIN PERFIL p ON pr.PERFIS_ID = p.ID 
INNER JOIN USUARIO u ON u.PERFIL_ID = p.ID
INNER JOIN ROLE r ON pr.ROLES_ID = r.id;

/*CONSULTA INDEPENDENTE DE USUARIO / PERFIL / ROLES*/
SELECT * FROM PERFIL p
INNER JOIN  ROLE_PERFIS pr ON pr.PERFIS_ID = p.ID 
INNER JOIN ROLE r ON pr.ROLES_ID = r.id
LEFT JOIN USUARIO u ON u.PERFIL_ID = p.ID;
